# TME 3.1 : Greedy Profile Motif Search 

Nom Etudiant 1: 28602815 Philippe TAN
<br>
Nom Etudiant 2: 28714617 Lasha GOGRITCHIANI

## Recheche de pattern (motifs) en utilisant les algoritmes randomisés

Les algorithmes randomisés prendre des décisions aléatoire plutôt que déterministes.
l'algorithme s'exécute différemment à chaque fois. Ils sont couramment utilisés dans situations où aucun algorithme exact et rapide est connu. Nous allons d'abord implémenter l'algorithm Greedy Profile Motif Search.



1\. Nous allons réutiliser les fonctions du precedent pour générer `t` séquences artificielles de taille `n`, et implanter dans chaque séquence un motif de taille `k` à des positions aléatoires avec `v` substitutions choisies aléatoirement. Nous allons faire varier le motifs dans 50% de cas.

In [1]:
import random
import numpy as np

nuc = ('A', 'C', 'G', 'T')

t=8 #taille de motif
v=1 #nb de positions variable dans le motif
k=8 #nb de sequences
n=10 #longuer des sequence
f= 0.5 #frequence de variation du motif.


In [2]:

def generateRandomSequence(n, upper=True):
    """
    Génère une séquence nucléotidique aléatoire 
    entrée n : longueur de la sequence
    entrée upper : bool, si True les nucléotides seront en majuscule, False minuscule
    sortie sequence : une séquence nucléotidique aléatoire 
    """
    sequence = ""

    random.seed(None)
    for i in range (0, n) :
        sequence += random.choice(nuc)
    
    if upper :
        sequence.lower()
   
    return sequence

def modifierMotif(motif, nbpos,  upper=True):
    """
    Modifie nbpos positions d'un motif aléatoirement 
    entrée motif: motif à modifier
    entrée nbpos: nombre de positions
    entrée upper : bool, si True les nucléotides modifiés seront majuscule, False minuscule
    sortie motifM: motif modifié
    """
    motifM = list(motif)
    motifM = [nt.upper() for nt in motifM]
    
    randpos = 0
    randpositions = set()
    mutation = ""
    
    i = 0
    while (i < nbpos):
        randpos = random.randint(0, len(motifM) - 1)
        if randpos not in randpositions :
            while (mutation == motifM[randpos] or mutation == ""):
                mutation = random.choice(nuc)
            motifM[randpos] = mutation
            randpositions.add(randpos)
            mutation = ""
            i += 1
    if upper :
        motifM = [nt.lower() for nt in motifM]
    
    return "".join(motifM)

#tester la fonction modifierMotif
print (modifierMotif("acg", 2))

def insertMotif(sequence, motif, position):
    return sequence[:position] + motif + sequence[position:]

def implantMotifVar(k, v, t, n, f):
    """
    Génère des séquences aléatoires et les implante des motifs variables (un motif par séquence)
    entrée k : nombre de séquences 
    entrée v: nombre de variations
    entrée t: taille du motif
    entrée n : longueur des séquences
    entrée f : frequence de variation du motif.
    sortie DNA : matrice de dimension txn avec les motifs implantés
    REMARQUE : La taille totale des séquences plus motif doit être égal à t, pensez à générer de séquence aléatoire de taille t-k pour pouvoir implanter un motif de taille k
    """
    #Création du motif de base
    motif = generateRandomSequence(t, False)
    print(motif)
    sequences = []
    
    #Génère les séquences où implanter les motifs variables
    sequences = [generateRandomSequence(n - t) for i in range(k)]

    for i in range(k) :
        #Variation du motif de v nucléotides
        motifM = motif
        if random.random() < f :
            motifM = modifierMotif(motif, v)
        #Position aléatoire dans les séquences où implanter le motif modifié
        pos = random.randint(0, t - k)
        sequences[i] = insertMotif(sequences[i], motifM, pos)

    return sequences

adn = implantMotifVar(k, v, t, n, f)
print (adn)

adn  = [s.upper() for s in adn]
print (adn)

ggg
AAATTGGT
['aagttggtAG', 'aaattgggCA', 'AAATTGGTGC', 'AAATTGGTGC', 'aaattgatGT', 'aaatttgtCG', 'AAATTGGTCA', 'AAATTGGTCC']
['AAGTTGGTAG', 'AAATTGGGCA', 'AAATTGGTGC', 'AAATTGGTGC', 'AAATTGATGT', 'AAATTTGTCG', 'AAATTGGTCA', 'AAATTGGTCC']


2\. Faire une fonction pour sélectionner des positions de départ aléatoirement `s = (s1, …,st)`.


In [3]:
#creating vector s
#Get t random positions from 0 to n - k
def generateRandomS(sequences, k):
    """
    Génère un vecteur de position aléatoires
    entrée sequences: matrice de dimension txn contenant les sequences
    entrée k: taille du motif
    sortie s: vecteur de position aléatoires, une position par séquence
    REMARQUE les positions doivent être inférieur à n-k, ou n est la taille de sequence
    """
    s = []
    
    t = len(sequences)
    n = len(sequences[0])
    
    for i in range (t) :
        r = random.randint(0, n - k)
        s.append(r)

    return s

s = generateRandomS(adn, k)
print (s)

[2, 2, 2, 0, 0, 1, 0, 0]


3\. Extraire les motifs en utilisant le vecteur `s`, et construire un profile (matrice de fréquence). 


In [4]:
#extract sequences from seqs
def extractSeqs(s, seqs, k):
    """
    Extraire les motifs des séquences à l'aide de positions s
    entrée s: vecteur contenant les positions de départs
    entrée seqs: matrice de dimension txn contenant les séquences
    entrée k: taille du motif
    sortie motifs: liste de motifs de taille k extrait des séquences
    """
    motifs = []
    
    t = len(seqs)
    n = len(seqs[0])
    
    for i in range(t) :
        if s[i] != -1:
            motifs.append(seqs[i][s[i]: s[i] + k])
        else :
            print('s[', i, '] = -1. Aucun motif probable trouvé.')
   
    return motifs

print(s, adn, k)
motifs = extractSeqs(s, adn, k)
print(motifs)


#Construire un profile = matrice de fréquence
def profile(motifs, k, nuc):
    """
    Construire une matrice de fréquence de dimension k x |nuc|
    entrée motifs: liste de motifs
    entrée k: taille du motif
    entrée nuc: alphabet
    sortie MF: matrice de fréquence
    """
    q = len(nuc)
    PWM = np.zeros((q, k))
    
    for s in motifs :
        for j in range(k) :
            if len(s) < k :
                continue
            l = s[j]
            if l == 'A':
                PWM[0][j] += 1
            if l == 'C':
                PWM[1][j] += 1
            if l == 'G':
                PWM[2][j] += 1
            if l == 'T':
                PWM[3][j] += 1
  
    return PWM

MF = profile(motifs, k, nuc)
print(MF,"\n")

#motifs2 = ['AGGTT', 'CGGTT', 'TAGAG', 'TTCCT', 'TTCTA', 'CGTCG']
#print(profile(motifs2, k, nuc))

[2, 2, 2, 0, 0, 1, 0, 0] ['AAGTTGGTAG', 'AAATTGGGCA', 'AAATTGGTGC', 'AAATTGGTGC', 'AAATTGATGT', 'AAATTTGTCG', 'AAATTGGTCA', 'AAATTGGTCC'] 8
['GTTGGTAG', 'ATTGGGCA', 'ATTGGTGC', 'AAATTGGT', 'AAATTGAT', 'AATTTGTC', 'AAATTGGT', 'AAATTGGT']
[[7. 5. 4. 0. 0. 0. 2. 1.]
 [0. 0. 0. 0. 0. 0. 1. 2.]
 [1. 0. 0. 3. 3. 6. 4. 1.]
 [0. 3. 4. 5. 5. 2. 1. 4.]] 



4\. Transformer la matrice de fréquence en PWM. Il faut diviser chaque élément par la somme de ses colonnes.

In [5]:
def generatePWM(MF):
    """
    Transforme la matrice de fréquence en PWM
    entrée MF: matrice de fréquence
    sortie PWM: matrice de probabilité (poids positions)
    """
    t = len(MF)
    n = len(MF[0])
    
    PWM = np.zeros((t, n))
    
    for i in range(n) :
        s = 0
        for j in range(t) :
            s += MF[j][i]
        for j in range(t) :
            PWM[j][i] = np.round(MF[j][i] / s, 2)
    
    return PWM
  
PWM = generatePWM(MF)
print(PWM)

[[0.88 0.62 0.5  0.   0.   0.   0.25 0.12]
 [0.   0.   0.   0.   0.   0.   0.12 0.25]
 [0.12 0.   0.   0.38 0.38 0.75 0.5  0.12]
 [0.   0.38 0.5  0.62 0.62 0.25 0.12 0.5 ]]


5\. Faire une fonction pour calculer la probabilité d'un motif de taille `k` selon une PWM.


In [6]:
def probability(PWM, motif):
    """
    Calcul la probalité d'un motif selon PWM
    entrée PWM: matrice de probabilité (poids positions)
    entrée motif: motif
    sortie prob: probalité Prob(motif|PWM)
    """
    if len(motif) > len(PWM[0]):
        print("La matrice de probabilité n'est pas assez grande.")
        return 0
    prob = 1
    lignes = {'A':0, 'C':1, 'G':2, 'T':3}
    
    for i, nuc in enumerate(motif) : 
        j = lignes[nuc]
        prob *= PWM[j][i]
        
    return prob

prob = probability(PWM, "AAAGA")
print (prob)

0.0


6\. Faire une fonction pour calculer le pMostProbkmer d'une séquence, voir un exemple dans les slides de cours.

In [7]:
def pMostProbkmer(PWM, k, sequence):
    """
    calcul la position du k-mer le plus probable dans la séquence
    entrée PWM: matrice de probabilité (poids positions)
    entrée k: taille du motif
    entrée sequence: séquence nucleotidique
    sortie s: la position la plus probable 
    """
    maxProb = 0
    s = 0 # position du k-mer le plus probable dans la sequence
    
    for i in range(len(sequence) - k + 1) :
        motif = sequence[i:i + k]
        prob = probability(PWM, motif)
        if prob > maxProb :
            maxProb = prob
            s = i
        i += 1
    
    return s
s = pMostProbkmer(PWM, k, "GCCGGATACT")
print (s)
print(adn)

0
['AAGTTGGTAG', 'AAATTGGGCA', 'AAATTGGTGC', 'AAATTGGTGC', 'AAATTGATGT', 'AAATTTGTCG', 'AAATTGGTCA', 'AAATTGGTCC']


7\. Faire une fonction pour obtenir les nouvelles positions de départ `s = (s1, …,st)`, c’était à dire les positions qui contiens les k-mer le plus probables.

In [8]:
def getNewS(PWM, k, sequences):
    """
    Trouve les nouvelles positions des k-mer le plus probables
    entrée PWM: matrice de probabilité (poids positions)
    entrée k: taille du motif
    entrée sequence: séquence nucleotidique
    sortie s: vecteur avec les positions les plus problables
    """
    s = []
    
    for seq in sequences :
        s.append(pMostProbkmer(PWM, k, seq))
   
    return s

ns = getNewS(PWM, k, adn)
print (ns)

[2, 1, 0, 0, 0, 0, 0, 0]


8\. La condition d’arrêt de l'algorithme est le non changement de la matrice de fréquence d'une itération à l'autre, 
faire une fonction pour comparer deux matrices et détecter le changement. 
Faire aussi une fonction pour obtenir le score d'une matrice de fréquence : la somme de max de chaque colonne

In [9]:
def changeProfile(P1, P2):
    """
    Compare deux matrice
    entrée P1: matrice de fréquence
    entrée P2: matrice de fréquence
    sortie: True si les matrices sont différents, False au contraire
    """
    if len(P1) != len(P2) :
        return False
    if len(P1[0]) != len(P2[0]) :
        return False
    t = len(P1)
    n = len(P1[0])
    
    for i in range(t) :
        for j in range(n) :
            if P1[i][j] != P2[i][j] :
                return False
    
    return True

def getScore(MF, k):
    """
    Renvoie le score de MF, la somme des max de chaque colonne
    entrée MF: matrice de fréquence
    entrée k: taille du motif
    sortie sc: score
    """
    sc = 0
    
    t = len(MF)
    n = len(MF[0])
    
    for i in range(n) :
        m = 0
        for j in range(t) :
            val = MF[j][i]
            if val > m :
                m = val
        sc += m
    
    return sc

ns = getNewS(PWM, k, adn)
print ("s :", s, "\nns :", ns)

P2 = [[0.67, 0.,   0.67], [0.,   0.33, 0.  ], [0.33, 0.33, 0], [0.,   0.33, 0.  ]] 
print("\nPWM et P2 différents :", changeProfile(PWM, P2))
print("PWM comparé lui-même :", changeProfile(PWM, PWM), "\n")

sc = getScore(MF, k)
print ("getScore :", sc)


s : 0 
ns : [2, 1, 0, 0, 0, 0, 0, 0]

PWM et P2 différents : False
PWM comparé lui-même : True 

getScore : 40.0


9\. Implementer l'algorithme ``GreedyProfileMotifSearch`` en utilisant les fonctions precedentes. 
BONUS: Pour ameliorer la performance vous pouvez abandonner les positions qui génèrent des motifs peu complexes.

In [10]:
def isLowComplexe(motif, m) :
    """
    Vérifie si le motif doit être éliminé en raison de sa simplicité,
    c'est-à-dire s'il a au moins m fois la même lettre ou s'il a deux lettres
    consécutives répétées.
    entrée : motif
    sortie : True si le motif doit être éliminé, False sinon
    """   
    
    if len(set(motif)) == 1 and len(motif) >= m: # si le motif contient une lettre m fois
        return True

    if len(set(motif)) >= 2 and len(motif) >= m :
        nuc = {'A':0, 'C':0, 'T':0, 'G':0}
        pairs = set()
        impairs = set()
        current = ""
        cpt = 0
        
        for i, letter in enumerate(motif) : #enumerate pour récupérer le nucléotide et son index
            nuc[letter] += 1
            
            if i%2 == 0 : #si lettre en position paire, on ajoute dans l'ensemble "pairs"
                pairs.add(motif[i])
            else : #sinon "impairs"
                impairs.add(motif[i])
                
        nbvalues = nuc.values()
        for i in nbvalues : #si on a au moins m occurrence d'un des nucléotides, alors le motif est SIMPLE
            if i >= m :
                return True
        if len(pairs) == 1 and len(impairs) == 1 : #si on a un pattern de deux lettres qui se répètent : SIMPLE
            return True
    
    return False

def GreedyProfileMotifSearch(sequences, k):
    """
    Implémente l'algorithme GreedyProfileMotifSearch 
    entrée sequences: matrice de dimension txn contenant les séquences 
    entrée k : taille du motif 
    sortie s : vecteur de positions de départ ayant le meilleur motif 
    sortie bestScore : le score associé à s
    """
    bestS = generateRandomS(sequences, k)
    bestMotifs = extractSeqs(bestS, sequences, k)
    bestProf = profile(bestMotifs, k, nuc)
    bestScore = getScore(bestProf, k)
    
    threshold = k // 4
    
    motifFound = True
    while motifFound:
        motifFound = False
        
        prof = profile(bestMotifs, k, nuc)
        PWM = generatePWM(prof)
        
        motifs = []  
        for seq in sequences:
            probkmer = pMostProbkmer(PWM, k, seq)
            kmer = seq[probkmer : probkmer + k]
            if not isLowComplexe(kmer, threshold):
                motifs.append(kmer)
            else:
                motifs.append(None)
        
        if motifFound:
            score = getScore(prof, k)
            if score > bestScore:
                bestS = motifs
                bestMotifs = extractSeqs(bestS, sequences, k)
                bestProf = prof
                bestScore = score
                motifFound = True
    
    s = [0] * len(sequences)
    for i, motif in enumerate(bestMotifs):
        pos = sequences[i].index(motif)
        s[i] = pos
    
    return s, bestScore

print (adn)
s, bestScore = GreedyProfileMotifSearch(adn, k)
motifs = extractSeqs(s, adn, k)
print(bestScore)
print (motifs)

['AAGTTGGTAG', 'AAATTGGGCA', 'AAATTGGTGC', 'AAATTGGTGC', 'AAATTGATGT', 'AAATTTGTCG', 'AAATTGGTCA', 'AAATTGGTCC']
38.0
['GTTGGTAG', 'ATTGGGCA', 'ATTGGTGC', 'ATTGGTGC', 'AAATTGAT', 'ATTTGTCG', 'AATTGGTC', 'AAATTGGT']


10\. Avez vous trouvez le motif implanté? Rexécuter l’algorithme plusieurs fois pour le trouver. 

Reponse: GTT

11\. Vous avez certainement observer que l’algorithme ne produire pas toujours la même sortie et que les résultats dépendent de la sélection aléatoire des positions de départ `s`. Pour augmenter nous chances de retrouvez les bons motifs, nous allons implémenter une version itérative ``GreedyProfileMotifSearchIte`` 
qui a chaque fois sauvegarde `s` et le score du profile associé à `s`, après `I` itération, l’algorithme renvoie le vecteur `s` ayant le plus grand score.

In [11]:
def GreedyProfileMotifSearchIte(sequences, k, It):
    """
    Implémente l'algorithme GreedyProfileMotifSearch iteratif
    entrée séquences: matrice de dimension txn contenant les séquences
    entrée k: taille du motif 
    entrée It: nombre d'iterations
    sortie positions: dictionnaire clé=score, valeur= vecteur s 
    sortie consensus: dictionnaire clé=score, valeur= sequence consensus du motif
    """
    pos = {}
    consensus = {}
    for i in range(It):
        s, score = GreedyProfileMotifSearch(sequences, k)
        pos[score] = s
        
        motifs = extractSeqs(s, sequences, k)
        prof = profile(motifs, k, nuc)
        pwm = generatePWM(prof)
        
        maxProb = 0
        bestMotif = ""
        for i in motifs :
            prob = probability(PWM, i)
            if prob > maxProb :
                maxProb = prob
                bestMotif = i
        
        consensus[score] = bestMotif
    #print(sequences)
        
    
    max_key = max(pos, key=pos.get)
    #motifs = extractSeqs(pos[max_key], sequences, k)
    #print(motifs)
    #print(max_key)
    return pos[max_key], consensus


s, consensus = GreedyProfileMotifSearchIte(adn, k, 50)

print ('s :', s)
print ('consensus :', consensus)

s : [2, 2, 2, 2, 2, 1, 2, 2]
consensus : {37.0: 'AAATTGGT', 47.0: 'ATTGGTGC', 41.0: 'AAATTGGT', 39.0: 'AAATTGAT', 43.0: 'AAATTGGT', 50.0: 'AAATTGGT', 44.0: 'AAATTGGT', 42.0: 'AAATTGGT', 48.0: 'AATTTGTC', 38.0: 'AAATTGGT', 45.0: 'AAATTGGT', 40.0: 'AAATTGGT', 46.0: 'AAATTGGT', 36.0: 'AAATTGGT'}


In [12]:
#Affiche les sequence consensus de top motifs
def printTopFMotifsScore(consensus, top):

    motifsSort = sorted(consensus.keys())
    motifsSort.reverse()
    for i in range(top):
      print (motifsSort[i], consensus[motifsSort[i]])

printTopFMotifsScore(consensus, 2)




50.0 AAATTGGT
48.0 AATTTGTC


12\. Tester algorithme  ``GreedyProfileMotifSearchIte`` sur vos données de chipSeq. N'oubliez pas de chercher les motifs dans le brin complémentaire et faire un merge de résultats.

In [13]:

def reverseComplement(seq):
    seq_dict = {'A':'T','T':'A','G':'C','C':'G'}
    return "".join([seq_dict[base] for base in reversed(seq)])

In [14]:
k=8

def readFasta(genome, n):
    sequence = []
    file = open(genome, "r")
    sequence = []
    for s in file:
        if s[0] != ">":
            sequence.append(s.strip().upper())
    sequenceStr = "".join(sequence)
    #sequence = [sequenceStr]
    sequence = [sequenceStr[i:i+n] for i in range(0, len(sequenceStr), n)]
    sequenceRet = [x for x in sequence if x]
    return sequenceRet

genome = "Sequence_by_Peaks_4.fasta"


sequencesChip   = readFasta(genome, n)
t = len(sequencesChip)
print (sequencesChip[8], t, k)
revSequences = [reverseComplement(m) for m in sequencesChip]

sequencesChip = sequencesChip + revSequences
sequencesRet = [x for x in sequencesChip if len(x) == n]
#print(sequencesRet, len(sequencesRet))
s, consensus = GreedyProfileMotifSearchIte(sequencesRet, k, 20)
printTopFMotifsScore(consensus, 10)


CAGCTCTGGC 2929 8
15362.0 ATTTTGGT
15343.0 ATATTGGT
15339.0 ATATTGGT
15306.0 ATATTGGT
15292.0 ATTTTGGT
15277.0 ATTTTGGT
15276.0 ATATTGGT
15271.0 AAATGGGT
15267.0 ATATTGGT
15240.0 AATTTGAT
